runtime: python39  # Specifies the Python version

entrypoint: gunicorn -w 4 -b :$PORT alienbot_flask:app  # How to start your app

# optional instance settings
instance_class: F2  # Optional: Increase the instance class for more power

# automatic scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5